mystr= "Waliya is learning python to excel in the field of IT!"
print(mystr)
print(mystr[4])
print(mystr[0:48])
print(mystr[0:])
print(mystr[5:78])
print(mystr[:])
print(mystr[0:83:2])
print(mystr[-88:-10])
print(mystr[-78:-5:2])
print(mystr[-80:-4:-2])
#string functions
print(mystr.count("i"))
print(mystr.isalnum())
print(mystr.isalpha())
print(mystr.endswith("IT!"))
print(mystr.upper())
print(mystr.lower())
print(mystr.capitalize())
print(mystr.replace("learning", "practicing"))
print(mystr.__add__("advance"))
print(mystr.isascii())
print(mystr.find("python"))