s1=set([1,2,4,6])
print(type(s1))
print(s1)
s1.add(9)
print(s1)
print(max(s1))
print(min(s1))
print(len(s1))
s2=set([3,5,7,5]) # because it is a set; so it will only print unique values
print(s2)
print(s1.union(s2))
print(s1.isdisjoint(s2))
print(s1.issubset(s2))
s2.remove(5)
print(s2)
s1.pop()
print(s1)
